### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [leftyio/gtm_pixel#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) We are seeing console error while trying to run the code. We are unable to enter any field details to run the code. Please resolve the issue.
![Screenshot 2021-10-27 6 46 42 PM](https://user-images.githubusercontent.com/53495700/139172171-31263677-9dbb-4174-9fac-0c3ba9f1098e.png)

**Comment by lejard-h** [comment]
HI @praveena-pappu, thanks for reviewing our template.

I fixed your issue and added tests, do I need to resubmit the template or you will just `git pull` the repo ?

**Comment by philpott** [comment]
Sorry for the delay. We'll re-review it no need for resubmitting the issue.

**Comment by lejard-h** [comment]
Hi @philpott,

Any news about the review ?

**Comment by lejard-h** [comment]
@praveena-pappu @philpott  Hello ! Is it possible to review please ?

**Comment by lejard-h** [comment]
Try again since it would be nice for our clients

@praveena-pappu @philpott

**Comment by philpott** [comment]
Thanks for the bump and sorry this fell off our radar. I've done the review and it should be available on the gallery shortly.

**Comment by lejard-h** [comment]
Thanks a lot @philpott
